version: "3.9"
services:

  web0:
    container_name: web0
    build:
      context: web0
      dockerfile: Dockerfile
    ports:
      - 80:80
  web1:
    container_name: web1
    build:
      context: web1
      dockerfile: Dockerfile
    ports:
      - 81:80
  web2:
    container_name: web2
    image: php:8.1-apache
    ports:
      - 825:80
    volumes:
      - ./web2:/var/www/html/:rw
